/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SsAmbulanceWlList {
    }
}
declare global {
    interface HTMLSsAmbulanceWlListElement extends Components.SsAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLSsAmbulanceWlListElement: {
        prototype: HTMLSsAmbulanceWlListElement;
        new (): HTMLSsAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ss-ambulance-wl-list": HTMLSsAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface SsAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ss-ambulance-wl-list": SsAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ss-ambulance-wl-list": LocalJSX.SsAmbulanceWlList & JSXBase.HTMLAttributes<HTMLSsAmbulanceWlListElement>;
        }
    }
}
